/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 * File: J_r.c
 *
 * MATLAB Coder version            : 23.2
 * C/C++ source code generated on  : 29-Oct-2024 18:41:09
 */

/* Include Files */
#include "J_r.h"
#include "helix_controller_rtwutil.h"
#include "rt_nonfinite.h"
#include <math.h>

/* Function Definitions */
/*
 * J_r_new
 *     Jr = J_r_new(L0,D,dL1,dL2,dL3,DX1,DX2,DX3,DY1,DY2,DY3,TH)
 *
 * Arguments    : double q[10]
 *                double L0
 *                double d
 *                double Jr[30]
 *                double x_r[3]
 * Return Type  : void
 */
void J_r(double q[10], double L0, double d, double Jr[30], double x_r[3])
{
  int i;
  /*     This function was generated by the Symbolic Math Toolbox version 23.2.
   */
  /*     22-Oct-2024 23:25:02 */
  for (i = 0; i < 10; i++) {
    if (q[i] == 0.0) {
      q[i] = 1.0E-12;
    }
  }
  double b_t138_tmp;
  double b_t152_tmp;
  double b_t160_tmp;
  double b_t339_tmp;
  double b_t378_tmp;
  double b_t464_tmp;
  double b_t465_tmp;
  double b_t480_tmp;
  double b_t481_tmp;
  double b_t520_tmp;
  double b_t521_tmp;
  double b_t532_tmp;
  double c_t464_tmp;
  double c_t465_tmp;
  double t10;
  double t100;
  double t101;
  double t11;
  double t114_tmp;
  double t115_tmp;
  double t129;
  double t12_tmp;
  double t130;
  double t138;
  double t138_tmp;
  double t148;
  double t149;
  double t14_tmp;
  double t150;
  double t151;
  double t152_tmp;
  double t153;
  double t158;
  double t159;
  double t16;
  double t160_tmp;
  double t161;
  double t162;
  double t171_tmp;
  double t181;
  double t189;
  double t18_tmp;
  double t201;
  double t202;
  double t203;
  double t204;
  double t205;
  double t20_tmp;
  double t213;
  double t213_tmp;
  double t215;
  double t216;
  double t216_tmp;
  double t217;
  double t217_tmp;
  double t218;
  double t219;
  double t22;
  double t220;
  double t221;
  double t225;
  double t225_tmp_tmp;
  double t229;
  double t23;
  double t230_tmp;
  double t231_tmp;
  double t232_tmp;
  double t236;
  double t237;
  double t238;
  double t238_tmp;
  double t239;
  double t24;
  double t249_tmp;
  double t25;
  double t253_tmp;
  double t253_tmp_tmp;
  double t255;
  double t26;
  double t268_tmp;
  double t27;
  double t272;
  double t273;
  double t279;
  double t28;
  double t280_tmp;
  double t290;
  double t292;
  double t2_tmp;
  double t300;
  double t30_tmp;
  double t31_tmp;
  double t325;
  double t326;
  double t32_tmp;
  double t330;
  double t339_tmp;
  double t33_tmp;
  double t34;
  double t35;
  double t354;
  double t354_tmp;
  double t355;
  double t359;
  double t36;
  double t360;
  double t362;
  double t362_tmp;
  double t363;
  double t37;
  double t370;
  double t371;
  double t372_tmp;
  double t375;
  double t375_tmp;
  double t378_tmp;
  double t379;
  double t38;
  double t382;
  double t382_tmp;
  double t389_tmp;
  double t39;
  double t391;
  double t3_tmp;
  double t403;
  double t40_tmp;
  double t410_tmp;
  double t410_tmp_tmp;
  double t411;
  double t411_tmp_tmp;
  double t41_tmp;
  double t42_tmp;
  double t437_tmp;
  double t43_tmp;
  double t44;
  double t440_tmp;
  double t447;
  double t447_tmp;
  double t45;
  double t454;
  double t455;
  double t456;
  double t456_tmp;
  double t457;
  double t457_tmp;
  double t458;
  double t459;
  double t46;
  double t460;
  double t461;
  double t461_tmp;
  double t462;
  double t463;
  double t464;
  double t464_tmp;
  double t465;
  double t465_tmp;
  double t47;
  double t48;
  double t480;
  double t480_tmp;
  double t481;
  double t481_tmp;
  double t49;
  double t496;
  double t499;
  double t4_tmp;
  double t50;
  double t500;
  double t501;
  double t502;
  double t503;
  double t508;
  double t509;
  double t51;
  double t510;
  double t511;
  double t514;
  double t514_tmp;
  double t516;
  double t517;
  double t518;
  double t519;
  double t52;
  double t520;
  double t520_tmp;
  double t521;
  double t521_tmp;
  double t523;
  double t526;
  double t53;
  double t532;
  double t532_tmp;
  double t533;
  double t534;
  double t54;
  double t55;
  double t56;
  double t57;
  double t58;
  double t5_tmp;
  double t63;
  double t67;
  double t68;
  double t69;
  double t6_tmp;
  double t7;
  double t70;
  double t71;
  double t72;
  double t73;
  double t74;
  double t75;
  double t76;
  double t77;
  double t78;
  double t79;
  double t8;
  double t81;
  double t82;
  double t87;
  double t88;
  double t9;
  double t94;
  double t95;
  double t95_tmp;
  double t96;
  double t96_tmp;
  double t97;
  t2_tmp = cos(q[0]);
  t3_tmp = sin(q[0]);
  t4_tmp = L0 + q[3];
  t5_tmp = L0 + q[6];
  t6_tmp = L0 + q[9];
  t7 = q[1] * 2.0;
  t8 = q[4] * 2.0;
  t9 = q[2] * 2.0;
  t10 = q[5] * 2.0;
  t11 = q[8] * 2.0;
  t12_tmp = q[1] * q[1];
  t14_tmp = q[4] * q[4];
  t16 = q[7] * q[7];
  t18_tmp = q[2] * q[2];
  t20_tmp = q[5] * q[5];
  t22 = q[8] * q[8];
  t23 = rt_powd_snf(q[8], 3.0);
  t28 = 1.0 / d;
  t24 = q[1] * t2_tmp;
  t25 = q[2] * t2_tmp;
  t26 = q[1] * t3_tmp;
  t27 = q[2] * t3_tmp;
  t30_tmp = t12_tmp + t18_tmp;
  t31_tmp = t14_tmp + t20_tmp;
  t32_tmp = t16 + t22;
  t33_tmp = t25 + t26;
  t34 = 1.0 / t30_tmp;
  t36 = 1.0 / t31_tmp;
  t38 = 1.0 / t32_tmp;
  t40_tmp = sqrt(t30_tmp);
  t41_tmp = sqrt(t31_tmp);
  t42_tmp = sqrt(t32_tmp);
  t35 = t34 * t34;
  t37 = t36 * t36;
  t39 = t38 * t38;
  t43_tmp = t24 - t27;
  t44 = 1.0 / t40_tmp;
  t46 = 1.0 / t41_tmp;
  t48 = 1.0 / t42_tmp;
  t50 = t28 * t40_tmp;
  t51 = t28 * t41_tmp;
  t52 = t28 * t42_tmp;
  t45 = rt_powd_snf(t44, 3.0);
  t47 = rt_powd_snf(t46, 3.0);
  t49 = rt_powd_snf(t48, 3.0);
  t53 = cos(t50);
  t54 = cos(t51);
  t55 = cos(t52);
  t56 = sin(t50);
  t57 = sin(t51);
  t58 = sin(t52);
  t63 = t8 * t54;
  t67 = t12_tmp * t53;
  t68 = t14_tmp * t54;
  t69 = t16 * t55;
  t70 = t18_tmp * t53;
  t71 = t20_tmp * t54;
  t87 = q[1] * t56 * t57;
  t88 = q[2] * t56 * t57;
  t96_tmp = q[2] * t4_tmp;
  t96 = t96_tmp * t24 * t45 * t56;
  t97 = t96_tmp * t26 * t45 * t56;
  t129 = t18_tmp * t24 * t28 * t45 * t56;
  t130 = t12_tmp * t25 * t28 * t45 * t56;
  t153 = t46 * t53 * t57;
  t160_tmp = q[4] * q[5];
  b_t160_tmp = t160_tmp * t47;
  t161 = t2_tmp * t44 * t54 * t56;
  t162 = t3_tmp * t44 * t54 * t56;
  t171_tmp = t160_tmp * t28;
  t523 = t171_tmp * t36;
  t201 = t33_tmp * t44;
  t181 = t201 * t54 * t56;
  t526 = t43_tmp * t44;
  t189 = t526 * t54 * t56;
  t218 = q[4] * t2_tmp * t44 * t46 * t56 * t57;
  t219 = q[5] * t2_tmp * t44 * t46 * t56 * t57;
  t220 = q[4] * t3_tmp * t44 * t46 * t56 * t57;
  t221 = q[5] * t3_tmp * t44 * t46 * t56 * t57;
  t204 = d * t3_tmp;
  t229 = t204 * t5_tmp * t44 * t46 * t56 * t57;
  t238_tmp = d * t2_tmp;
  t238 = t238_tmp * t5_tmp * t44 * t46 * t56 * t57;
  t255 = t201 * t46 * t56 * t57;
  t279 = t526 * t46 * t56 * t57;
  t300 = t160_tmp * t43_tmp * t44 * t47 * t56 * t57;
  t72 = t12_tmp + t70;
  t73 = t18_tmp + t67;
  t74 = t14_tmp + t71;
  t75 = t20_tmp + t68;
  t76 = t22 + t69;
  t77 = t24 * t34 * (t53 - 1.0);
  t78 = t25 * t34 * (t53 - 1.0);
  t79 = t26 * t34 * (t53 - 1.0);
  t94 = t238_tmp * t4_tmp * t34 * (t53 - 1.0);
  t95_tmp = t204 * t4_tmp;
  t95 = t95_tmp * t34 * (t53 - 1.0);
  t100 = q[4] * t87;
  t101 = q[5] * t88;
  t526 = t2_tmp * t7;
  t114_tmp = q[2] * t7;
  t115_tmp = t3_tmp * t7;
  t138_tmp = d * t4_tmp;
  b_t138_tmp = t138_tmp * t7;
  t138 = b_t138_tmp * t25 * t35 * (t53 - 1.0);
  t158 = q[4] * t153;
  t159 = q[5] * t153;
  t213_tmp = q[1] * q[4];
  t213 = t213_tmp * t36 * t44 * t56 * (t54 - 1.0);
  t52 = q[2] * q[4];
  t215 = t52 * t36 * t44 * t56 * (t54 - 1.0);
  t216_tmp = t160_tmp * t36;
  t216 = t216_tmp * t44 * t56 * (t54 - 1.0);
  t217_tmp = q[2] * q[5];
  t217 = t217_tmp * t36 * t44 * t56 * (t54 - 1.0);
  t225_tmp_tmp = t213_tmp * q[2];
  t51 = t225_tmp_tmp * q[5];
  t225 = t51 * t36 * t45 * t56 * (t54 - 1.0);
  t231_tmp = q[5] * t28;
  t232_tmp = q[4] * t28;
  t239 = t51 * t28 * t34 * t36 * t53 * (t54 - 1.0);
  t249_tmp = t171_tmp * t34 * t36 * (t54 - 1.0);
  t272 = q[4] * t255;
  t273 = q[5] * t255;
  t290 = q[4] * t279;
  t292 = q[5] * t279;
  t330 = t523 * t189;
  t339_tmp = t28 * t36;
  b_t339_tmp = t339_tmp * t43_tmp * t44 * t56;
  t81 = q[2] * t77;
  t82 = q[2] * t79;
  t238_tmp = t2_tmp * t34;
  t518 = t3_tmp * t34;
  t148 = t7 - q[1] * t18_tmp * t28 * t44 * t56;
  t519 = q[4] * t20_tmp * t28;
  t149 = t8 - t519 * t46 * t57;
  t150 = t9 - q[2] * t12_tmp * t28 * t44 * t56;
  t517 = q[5] * t14_tmp * t28;
  t151 = t10 - t517 * t46 * t57;
  t152_tmp = q[8] * t16;
  b_t152_tmp = t152_tmp * t28;
  t201 = t7 * t53 - rt_powd_snf(q[1], 3.0) * t28 * t44 * t56;
  t202 = t63 - rt_powd_snf(q[4], 3.0) * t28 * t46 * t57;
  t203 = q[7] * t55 * 2.0 - rt_powd_snf(q[7], 3.0) * t28 * t48 * t58;
  t204 = t9 * t53 - rt_powd_snf(q[2], 3.0) * t28 * t44 * t56;
  t205 = t10 * t54 - rt_powd_snf(q[5], 3.0) * t28 * t46 * t57;
  t230_tmp = t28 * t44 * t46;
  t51 = t36 * t44 * t56;
  t236 = t51 * t74;
  t237 = t51 * t75;
  t253_tmp_tmp = q[1] * q[2];
  t253_tmp = t253_tmp_tmp * t36 * t45 * t56;
  t268_tmp = t253_tmp_tmp * t28 * t34 * t36 * t53;
  t280_tmp = t28 * t34 * t36;
  t447_tmp = t40_tmp * t41_tmp;
  t447 = (t100 + t101) - t447_tmp * t53 * t54;
  t464_tmp = d * q[4];
  b_t464_tmp = d * q[1];
  c_t464_tmp = t253_tmp_tmp * q[5];
  t464 = (((c_t464_tmp * t53 * t57 + q[4] * t57 * t67) +
           t464_tmp * t40_tmp * t56 * t57) -
          b_t464_tmp * t41_tmp * t53 * t54) +
         q[1] * t40_tmp * t41_tmp * t54 * t56;
  t465_tmp = d * q[2];
  b_t465_tmp = d * q[5];
  c_t465_tmp = b_t465_tmp * t40_tmp;
  t465 = (((t225_tmp_tmp * t53 * t57 + q[5] * t57 * t70) +
           c_t465_tmp * t56 * t57) -
          t465_tmp * t41_tmp * t53 * t54) +
         q[2] * t40_tmp * t41_tmp * t54 * t56;
  t480_tmp = q[1] * t28;
  b_t480_tmp = t52 * q[5];
  t480 =
      (((t87 + q[4] * t50 * t53 * t57) + b_t480_tmp * t28 * t46 * t54 * t56) +
       t480_tmp * t46 * t56 * t68) -
      q[4] * t40_tmp * t46 * t53 * t54;
  t481_tmp = q[2] * t28;
  b_t481_tmp = t213_tmp * q[5];
  t481 =
      (((t88 + q[5] * t50 * t53 * t57) + b_t481_tmp * t28 * t46 * t54 * t56) +
       t481_tmp * t46 * t56 * t71) -
      q[5] * t40_tmp * t46 * t53 * t54;
  t325 = t82 + t238_tmp * t72;
  t326 = t81 + t518 * t73;
  t375_tmp = t81 - t518 * t72;
  t375 = -q[4] * t36 * (t54 - 1.0) * t375_tmp;
  t378_tmp = -q[5] * t36 * (t54 - 1.0);
  b_t378_tmp = t82 - t238_tmp * t73;
  t379 = t378_tmp * t375_tmp;
  t382_tmp = -q[4] * q[5];
  t382 = t382_tmp * t47 * t57 * b_t378_tmp;
  t391 = -t14_tmp * t47 * t57 * b_t378_tmp;
  t51 = q[4] * t36 * (t54 - 1.0);
  t403 = t51 * b_t378_tmp;
  t410_tmp_tmp = t14_tmp * t47;
  t410_tmp = t410_tmp_tmp * t57;
  t411_tmp_tmp = t20_tmp * t47;
  t52 = t411_tmp_tmp * t57;
  t411 = t52 * t375_tmp;
  t437_tmp = q[4] * t37;
  t440_tmp = q[5] * t37;
  t354_tmp = t46 * t57;
  t354 = t354_tmp * t325;
  t355 = t354_tmp * t326;
  t50 = t51 * t325;
  t359 = t51 * t326;
  t82 = q[5] * t36 * (t54 - 1.0);
  t360 = t82 * t325;
  t362_tmp = b_t160_tmp * t57;
  t362 = t362_tmp * t325;
  t363 = t362_tmp * t326;
  t370 = t410_tmp * t326;
  t371 = t52 * t325;
  t372_tmp = t523 * t54;
  t389_tmp = t339_tmp * t68;
  t454 = (t158 + q[5] * t215) + q[1] * t237;
  t455 = (t159 + q[5] * t213) + q[2] * t236;
  t456_tmp = -t78 + t114_tmp * t24 * t35 * (t53 - 1.0);
  t456 = ((t456_tmp + t130) + t26 * t35 * t72 * -2.0) + t518 * t148;
  t457_tmp = (-t79 + t115_tmp * t18_tmp * t35 * (t53 - 1.0)) +
             t18_tmp * t26 * t28 * t45 * t56;
  t457 = (t457_tmp + t25 * t35 * t73 * -2.0) + t238_tmp * t150;
  t52 = -t77 + t526 * t18_tmp * t35 * (t53 - 1.0);
  t460 = ((t52 + t129) + t27 * t35 * t72 * -2.0) + t518 * t204;
  t461_tmp = (-t27 * t34 * (t53 - 1.0) + t114_tmp * t26 * t35 * (t53 - 1.0)) +
             t12_tmp * t27 * t28 * t45 * t56;
  t461 = (t461_tmp + t24 * t35 * t73 * -2.0) + t238_tmp * t201;
  t51 = t339_tmp * t53;
  t81 = q[1] * t36 * t44 * t56;
  t510 = ((((((t153 - t410_tmp_tmp * t53 * t57) + t51 * t68) + t217) +
            t217_tmp * t14_tmp * t37 * t44 * t56 * (t54 - 1.0) * -2.0) +
           t213_tmp * t37 * t44 * t56 * t75 * -2.0) -
          t14_tmp * t28 * t44 * t47 * t101) +
         t81 * t202;
  t171_tmp = q[2] * t36 * t44 * t56;
  t511 = ((((((t153 - t411_tmp_tmp * t53 * t57) + t51 * t71) + t213) +
            t213_tmp * t20_tmp * t37 * t44 * t56 * (t54 - 1.0) * -2.0) +
           t217_tmp * t37 * t44 * t56 * t74 * -2.0) -
          t20_tmp * t28 * t44 * t47 * t100) +
         t171_tmp * t205;
  t51 = -t46 * t57;
  t514_tmp = -t28 * t36;
  t514 = ((((t28 * t292 + t51 * t375_tmp) + t382) + t514_tmp * t71 * t375_tmp) +
          t411) +
         t372_tmp * b_t378_tmp;
  t534 = ((((((t279 - t20_tmp * t43_tmp * t44 * t47 * t56 * t57) +
              b_t339_tmp * t71) +
             t403) +
            -t8 * t20_tmp * t37 * (t54 - 1.0) * b_t378_tmp) +
           -q[4] * t20_tmp * t28 * t47 * t57 * b_t378_tmp) +
          t440_tmp * t74 * t375_tmp * 2.0) +
         -t36 * t205 * t375_tmp;
  t458 = ((t52 + t3_tmp * t9 * t35 * t73) + t129) - t518 * t150;
  t459 = (t461_tmp + t526 * t35 * t72) - t238_tmp * t148;
  t462 = ((t456_tmp + t115_tmp * t35 * t73) + t130) - t518 * t201;
  t463 = (t457_tmp + t2_tmp * t9 * t35 * t72) - t238_tmp * t204;
  t526 = q[5] * t46 * t57;
  t499 = (t189 + q[4] * (t51 * b_t378_tmp)) + t526 * t375_tmp;
  t410_tmp_tmp = t36 * t75;
  t502 = (t290 + q[5] * t375) + t410_tmp_tmp * b_t378_tmp;
  t503 = (t292 + q[5] * t403) + -t36 * t74 * t375_tmp;
  t51 = b_t160_tmp * t53 * t57 - t523 * t53 * t54;
  t52 = q[2] * t8;
  t115_tmp = q[5] * t7;
  t508 = ((((t51 - q[1] * q[5] * t36 * t44 * t56 * (t54 - 1.0)) +
            t115_tmp * t14_tmp * t37 * t44 * t56 * (t54 - 1.0)) +
           t52 * t37 * t44 * t56 * t74) +
          t517 * t44 * t47 * t87) -
         t171_tmp * t149;
  t509 = ((((t51 - t215) + t52 * t20_tmp * t37 * t44 * t56 * (t54 - 1.0)) +
           t115_tmp * t37 * t44 * t56 * t75) +
          t519 * t44 * t47 * t88) -
         t81 * t151;
  t496 = (t181 + q[4] * t355) + q[5] * t354;
  t500 = (-t272 + q[5] * t50) + t410_tmp_tmp * t326;
  t238_tmp = t36 * t74;
  t501 = (-t273 + q[5] * t359) + t238_tmp * t325;
  t51 = -(t160_tmp * t33_tmp * t44 * t47 * t56 * t57) + t523 * t181;
  t520_tmp = t160_tmp * t8 * t37 * (t54 - 1.0);
  t129 = t8 * t37;
  b_t520_tmp = t36 * t149;
  t520 = ((((t51 - t82 * t326) + t520_tmp * t326) + t129 * t74 * t325) +
          t231_tmp * t370) -
         b_t520_tmp * t325;
  t521_tmp = t8 * t20_tmp * t37 * (t54 - 1.0);
  t52 = t10 * t37;
  b_t521_tmp = t36 * t151;
  t521 =
      ((((t51 - t50) + t521_tmp * t325) + t52 * t75 * t326) + t232_tmp * t371) -
      b_t521_tmp * t326;
  t51 = t28 * t33_tmp * t36 * t44 * t56;
  t532_tmp = t36 * t202;
  b_t532_tmp = t517 * t47 * t57;
  t532 = ((((((t255 - t14_tmp * t33_tmp * t44 * t47 * t56 * t57) + t51 * t68) -
             t360) +
            t520_tmp * t325) +
           t129 * t75 * t326) +
          b_t532_tmp * t325) -
         t532_tmp * t326;
  t533 = ((((((t255 - t20_tmp * t33_tmp * t44 * t47 * t56 * t57) + t51 * t71) -
             t359) +
            t521_tmp * t326) +
           t52 * t74 * t325) +
          t519 * t47 * t57 * t326) -
         t36 * t205 * t325;
  t51 = q[4] * t46 * t57;
  t52 = t481_tmp * t33_tmp * t34;
  t516 = (((-t161 + q[2] * t33_tmp * t45 * t54 * t56) - t52 * t53 * t54) +
          t51 * t458) +
         t526 * t463;
  t72 = t480_tmp * t33_tmp * t34;
  t517 = (((-t162 + q[1] * t33_tmp * t45 * t54 * t56) - t72 * t53 * t54) +
          t526 * t459) +
         t51 * t462;
  t130 = t480_tmp * t34 * t43_tmp;
  t518 = (((t161 + t130 * t53 * t54) - q[1] * t43_tmp * t45 * t54 * t56) -
          t526 * t456) +
         t51 * t461;
  t292 = t481_tmp * t34 * t43_tmp;
  t519 = (((t162 + q[2] * t43_tmp * t45 * t54 * t56) - t292 * t53 * t54) -
          t51 * t457) +
         t526 * t460;
  t73 = t216_tmp * (t54 - 1.0);
  t151 = (((t218 - q[4] * t33_tmp * t45 * t46 * t88) + t52 * t158) +
          t410_tmp_tmp * t458) +
         t73 * t463;
  t51 = t33_tmp * t45 * t46;
  t523 = (((t219 - t51 * t101) + t52 * t159) + t73 * t458) + t238_tmp * t463;
  t148 =
      (((t220 - t51 * t100) + t72 * t158) + t73 * t459) + t410_tmp_tmp * t462;
  t150 = (((t221 - q[5] * t33_tmp * t45 * t46 * t87) + t72 * t159) +
          t238_tmp * t459) +
         t73 * t462;
  t51 = t43_tmp * t45 * t46;
  t526 =
      (((t218 - t51 * t100) + t130 * t158) + t73 * t456) - t410_tmp_tmp * t461;
  t52 = (((t219 - q[5] * t43_tmp * t45 * t46 * t87) + t130 * t159) +
         t238_tmp * t456) -
        t73 * t461;
  t149 = (((t220 + q[4] * t43_tmp * t45 * t46 * t88) - t292 * t158) +
          t410_tmp_tmp * t457) -
         t73 * t460;
  t51 = (((t221 + t51 * t101) - t292 * t159) + t73 * t457) - t238_tmp * t460;
  t461_tmp = d * t5_tmp;
  t456_tmp = t38 * t76;
  t457_tmp = q[7] * t48 * t58;
  t201 = q[7] * q[8];
  t204 = t201 * t38 * (t55 - 1.0);
  t115_tmp = d * t6_tmp;
  t129 = t115_tmp * t48 * t58;
  t73 = d * q[7];
  t480_tmp = t73 * t6_tmp;
  t72 = t480_tmp * t38 * (t55 - 1.0);
  b_t160_tmp = d * q[8];
  t481_tmp = b_t160_tmp * t6_tmp;
  t215 = t481_tmp * t38 * (t55 - 1.0);
  Jr[0] = (((((((-0.0001 * ((t456_tmp * t500 - t457_tmp * t496) + t204 * t501) +
                 t138_tmp * t78) +
                t138_tmp * t79) -
               t461_tmp * t255) +
              t461_tmp * t359) +
             t461_tmp * t360) -
            t129 * t496) +
           t72 * t500) +
          t215 * t501;
  Jr[1] = (((((((-0.0001 * ((t456_tmp * t502 + t457_tmp * t499) + t204 * t503) +
                 t138_tmp * (t27 * t34 * (t53 - 1.0))) +
                t138_tmp * -t77) +
               t461_tmp * t279) +
              t461_tmp * t379) +
             t461_tmp * t403) +
            t129 * t499) +
           t72 * t502) +
          t215 * t503;
  Jr[2] = 0.0;
  t171_tmp = q[1] * t5_tmp;
  t202 = t464_tmp * t5_tmp;
  t81 = t202 * t36;
  t82 = t81 * (t54 - 1.0);
  t205 = b_t465_tmp * t5_tmp;
  t50 = t205 * t36;
  t216_tmp = t50 * (t54 - 1.0);
  t410_tmp_tmp = t461_tmp * t43_tmp * t45 * t46;
  t411_tmp_tmp = t2_tmp * t4_tmp;
  t114_tmp = t465_tmp * t4_tmp;
  Jr[3] =
      ((((((((((((-t97 - t94) + t238) -
                0.0001 * ((t456_tmp * t526 + t457_tmp * t518) + t204 * t52)) +
               t129 * t518) +
              t171_tmp * t34 * t43_tmp * t153) +
             t411_tmp_tmp * t12_tmp * t45 * t56) +
            b_t138_tmp * t24 * t35 * (t53 - 1.0)) -
           t410_tmp_tmp * t87) -
          t82 * t461) +
         t72 * t526) -
        t114_tmp * t26 * t35 * (t53 - 1.0) * 2.0) +
       t216_tmp * t456) +
      t215 * t52;
  t526 = t3_tmp * t4_tmp;
  t238_tmp = t461_tmp * t33_tmp * t45 * t46;
  Jr[4] =
      ((((((((((((-t95 + t96) + t138) + t229) -
               0.0001 * ((t456_tmp * t148 - t457_tmp * t517) + t204 * t150)) -
              t129 * t517) +
             t171_tmp * t33_tmp * t34 * t153) +
            t526 * t12_tmp * t45 * t56) +
           b_t138_tmp * t26 * t35 * (t53 - 1.0)) -
          t238_tmp * t87) +
         t82 * t462) +
        t72 * t148) +
       t216_tmp * t459) +
      t215 * t150;
  t171_tmp = ((((t225 + t230_tmp * t100) - t237) - t239) +
              t12_tmp * t36 * t45 * t56 * t75) -
             t280_tmp * t67 * t75;
  t52 = ((((t216 - t231_tmp * t44 * t46 * t87) -
           t160_tmp * t12_tmp * t36 * t45 * t56 * (t54 - 1.0)) +
          t249_tmp * t67) -
         t253_tmp * t74) +
        t268_tmp * t74;
  t130 = q[7] * t28 * t34 * t46 * t48 * t58;
  t292 = t5_tmp * t44 * t46;
  t150 = t6_tmp * t34 * t46 * t48 * t58;
  t148 = q[4] * t5_tmp;
  t518 = q[1] * q[7];
  Jr[5] = (((((((((((0.0001 * (((t456_tmp * t171_tmp - t204 * t52) -
                                t518 * t45 * t46 * t48 * t58 * t447) +
                               t130 * t464) +
                     q[1] * t4_tmp * t34 * t53) -
                    t292 * t87) -
                   b_t464_tmp * t4_tmp * t45 * t56) +
                  t148 * t34 * t36 * (t54 - 1.0) * t67) -
                 t150 * t464) -
                t72 * t171_tmp) +
               t215 * t52) +
              t81 * t44 * t56 * (t54 - 1.0)) +
             c_t464_tmp * t5_tmp * t34 * t36 * t53 * (t54 - 1.0)) -
            t202 * t12_tmp * t36 * t45 * t56 * (t54 - 1.0)) +
           b_t464_tmp * t6_tmp * t45 * t46 * t48 * t58 * t447) -
          b_t464_tmp * q[2] * q[5] * t5_tmp * t36 * t45 * t56 * (t54 - 1.0);
  t171_tmp = q[2] * t5_tmp;
  Jr[6] =
      ((((((((((((t95 + t96) + t138) - t229) +
               0.0001 * ((t456_tmp * t149 + t457_tmp * t519) + t204 * t51)) -
              t129 * t519) +
             t171_tmp * t34 * t43_tmp * t153) -
            t526 * t18_tmp * t45 * t56) -
           t95_tmp * t18_tmp * t35 * (t53 - 1.0) * 2.0) -
          t410_tmp_tmp * t88) -
         t82 * t457) -
        t72 * t149) +
       t216_tmp * t460) -
      t215 * t51;
  Jr[7] =
      ((((((((((((t97 - t94) + b_t138_tmp * t27 * t35 * (t53 - 1.0)) + t238) -
               0.0001 * ((t456_tmp * t151 - t457_tmp * t516) + t204 * t523)) -
              t129 * t516) +
             t171_tmp * t33_tmp * t34 * t153) +
            t411_tmp_tmp * t18_tmp * t45 * t56) +
           t138_tmp * t9 * t25 * t35 * (t53 - 1.0)) -
          t238_tmp * t88) +
         t82 * t458) +
        t72 * t151) +
       t216_tmp * t463) +
      t215 * t523;
  t171_tmp = ((((t216 - t232_tmp * t44 * t46 * t88) -
                t160_tmp * t18_tmp * t36 * t45 * t56 * (t54 - 1.0)) +
               t249_tmp * t70) -
              t253_tmp * t75) +
             t268_tmp * t75;
  t81 = ((((t225 + t230_tmp * t101) - t236) - t239) +
         t18_tmp * t36 * t45 * t56 * t74) -
        t280_tmp * t70 * t74;
  t82 = q[5] * t5_tmp;
  t216_tmp = b_t464_tmp * q[4];
  Jr[8] = (((((((((((-0.0001 * (((t456_tmp * t171_tmp - t204 * t81) +
                                 q[2] * q[7] * t45 * t46 * t48 * t58 * t447) -
                                t130 * t465) +
                     t96_tmp * t34 * t53) -
                    t292 * t88) -
                   t114_tmp * t45 * t56) +
                  t82 * t34 * t36 * (t54 - 1.0) * t70) -
                 t150 * t465) +
                t72 * t171_tmp) -
               t215 * t81) +
              t50 * t44 * t56 * (t54 - 1.0)) +
             t225_tmp_tmp * t5_tmp * t34 * t36 * t53 * (t54 - 1.0)) -
            t205 * t18_tmp * t36 * t45 * t56 * (t54 - 1.0)) +
           t465_tmp * t6_tmp * t45 * t46 * t48 * t58 * t447) -
          t216_tmp * q[2] * t5_tmp * t36 * t45 * t56 * (t54 - 1.0);
  Jr[9] = -d * t34 * t43_tmp * (t53 - 1.0);
  Jr[10] = -d * t33_tmp * t34 * (t53 - 1.0);
  t171_tmp = d * t44;
  Jr[11] = t171_tmp * t56;
  t81 = ((((t28 * t290 + t391) + t382_tmp * t28 * t36 * t54 * t375_tmp) +
          t354_tmp * b_t378_tmp) +
         t389_tmp * b_t378_tmp) +
        t362_tmp * t375_tmp;
  t50 = ((((((t279 - t14_tmp * t43_tmp * t44 * t47 * t56 * t57) +
             b_t339_tmp * t68) +
            t379) -
           t437_tmp * t75 * b_t378_tmp * 2.0) +
          t532_tmp * b_t378_tmp) +
         t520_tmp * t375_tmp) +
        b_t532_tmp * t375_tmp;
  t410_tmp_tmp = (((((t300 - t330) + t378_tmp * b_t378_tmp) -
                    t437_tmp * t74 * t375_tmp * 2.0) +
                   t231_tmp * (t410_tmp * b_t378_tmp)) +
                  b_t520_tmp * t375_tmp) +
                 t520_tmp * b_t378_tmp;
  t411_tmp_tmp = t148 * t36;
  t114_tmp = t461_tmp * t36 * (t54 - 1.0);
  t526 = t202 * t8 * t37 * (t54 - 1.0);
  Jr[12] = ((((t5_tmp * t391 + 0.0001 * ((-t38 * t76 * t50 + t457_tmp * t81) +
                                         t204 * t410_tmp_tmp)) +
              t411_tmp_tmp * t189) +
             t114_tmp * b_t378_tmp) -
            t129 * t81) +
           (((((t160_tmp * t5_tmp * t47 * t57 * t375_tmp + t72 * t50) -
               t215 * t410_tmp_tmp) +
              t464_tmp * q[5] * t5_tmp * t37 * (t54 - 1.0) * t375_tmp * 2.0) -
             t526 * b_t378_tmp) -
            t202 * t43_tmp * t44 * t47 * t56 * t57);
  t81 = ((((t28 * t272 - t355) + t362) + t370) - t372_tmp * t325) -
        t389_tmp * t326;
  t50 = t205 * t8 * t37 * (t54 - 1.0);
  Jr[13] =
      (((((((((-0.0001 * ((t456_tmp * t532 - t457_tmp * t81) + t204 * t520) +
               t5_tmp * t362) +
              t5_tmp * t370) +
             t411_tmp_tmp * t181) -
            t129 * t81) -
           t114_tmp * t326) +
          t72 * t532) +
         t215 * t520) +
        t526 * t326) +
       t50 * t325) -
      t202 * t33_tmp * t44 * t47 * t56 * t57;
  t81 = b_t464_tmp * t5_tmp;
  t410_tmp_tmp = q[7] * t44 * t46 * t48 * t58;
  t526 = t115_tmp * t44 * t46 * t48 * t58;
  t238_tmp = q[4] * q[7];
  Jr[14] =
      ((((((((((-0.0001 *
                    (((t456_tmp * t510 - t204 * t508) - t410_tmp_tmp * t480) +
                     t238_tmp * t44 * t47 * t48 * t58 * t447) +
                t411_tmp_tmp * t53 * t54) -
               t148 * t44 * t47 * t101) -
              t5_tmp * t14_tmp * t44 * t47 * t87) -
             t202 * t47 * t53 * t57) +
            t72 * t510) -
           t215 * t508) +
          t81 * t36 * t44 * t56 * (t54 - 1.0)) -
         t526 * t480) -
        t81 * t14_tmp * t37 * t44 * t56 * (t54 - 1.0) * 2.0) +
       t464_tmp * t6_tmp * t44 * t47 * t48 * t58 * t447) -
      t464_tmp * q[2] * q[5] * t5_tmp * t37 * t44 * t56 * (t54 - 1.0) * 2.0;
  t81 = (((((-t300 + t330) + t375) - t440_tmp * t75 * b_t378_tmp * 2.0) +
          t232_tmp * t411) +
         b_t521_tmp * b_t378_tmp) +
        t521_tmp * t375_tmp;
  t411_tmp_tmp = t82 * t36;
  Jr[15] =
      (((((((((-0.0001 * ((t456_tmp * t81 - t457_tmp * t514) + t204 * t534) +
               t5_tmp * t382) +
              t5_tmp * t411) +
             t411_tmp_tmp * t189) -
            t129 * t514) -
           t114_tmp * t375_tmp) +
          t461_tmp * t20_tmp * t37 * (t54 - 1.0) * t375_tmp * 2.0) +
         t72 * t81) +
        t215 * t534) -
       t50 * b_t378_tmp) -
      t205 * t43_tmp * t44 * t47 * t56 * t57;
  t461_tmp = ((((t28 * t273 - t354) + t363) + t371) - t372_tmp * t326) -
             t339_tmp * t71 * t325;
  Jr[16] = (((((((((-0.0001 * ((t456_tmp * t521 - t457_tmp * t461_tmp) +
                               t204 * t533) +
                    t5_tmp * t363) +
                   t5_tmp * t371) +
                  t411_tmp_tmp * t181) -
                 t129 * t461_tmp) -
                t114_tmp * t325) +
               t72 * t521) +
              t215 * t533) +
             t50 * t326) +
            t205 * t10 * t37 * (t54 - 1.0) * t325) -
           t205 * t33_tmp * t44 * t47 * t56 * t57;
  t461_tmp = t465_tmp * t5_tmp;
  t457_tmp = t216_tmp * q[5];
  Jr[17] =
      ((((((((((0.0001 *
                    (((t456_tmp * t509 - t204 * t511) + t410_tmp_tmp * t481) -
                     q[5] * q[7] * t44 * t47 * t48 * t58 * t447) +
                t411_tmp_tmp * t53 * t54) -
               t82 * t44 * t47 * t100) -
              t5_tmp * t20_tmp * t44 * t47 * t88) -
             t72 * t509) -
            t205 * t47 * t53 * t57) +
           t215 * t511) +
          t461_tmp * t36 * t44 * t56 * (t54 - 1.0)) -
         t526 * t481) -
        t461_tmp * t20_tmp * t37 * t44 * t56 * (t54 - 1.0) * 2.0) +
       b_t465_tmp * t6_tmp * t44 * t47 * t48 * t58 * t447) -
      t457_tmp * t5_tmp * t37 * t44 * t56 * (t54 - 1.0) * 2.0;
  Jr[18] = (d * t279 + d * t379) + d * t403;
  Jr[19] = (d * t255 + d * -t359) + d * -t360;
  Jr[20] = (d * t153 + d * t213) + d * t217;
  t461_tmp = t48 * t58;
  t456_tmp = t38 * t203;
  t204 = q[7] * t39 * t76;
  t129 = q[8] * t38 * (t55 - 1.0);
  t72 = t16 * t49 * t58;
  t215 = t28 * t38;
  t81 = t215 * t69;
  t82 = b_t152_tmp * t49 * t58;
  t50 = t115_tmp * t38 * (t55 - 1.0);
  t410_tmp_tmp = q[7] * t6_tmp * t38;
  t411_tmp_tmp = t410_tmp_tmp * t55;
  t114_tmp = t6_tmp * t16 * t49 * t58;
  t526 = t115_tmp * t16 * t39 * (t55 - 1.0);
  t52 = t480_tmp * t49 * t58;
  t130 = t201 * t6_tmp * t49 * t58;
  t292 = t73 * q[8];
  t150 = t292 * t6_tmp * t39 * (t55 - 1.0);
  Jr[21] =
      ((((((-0.0001 *
                (((((((t461_tmp * t499 + t456_tmp * t502) - t204 * t502 * 2.0) +
                     t129 * t503) -
                    t72 * t499) +
                   t81 * t499) -
                  t152_tmp * t39 * (t55 - 1.0) * t503 * 2.0) -
                 t82 * t503) +
            t50 * t502) +
           t411_tmp_tmp * t499) -
          t114_tmp * t502) -
         t526 * t502 * 2.0) -
        t52 * t499) -
       t130 * t503) -
      t150 * t503 * 2.0;
  t148 = t11 * t16 * t39 * (t55 - 1.0);
  t51 = t480_tmp * t11 * t39 * (t55 - 1.0);
  Jr[22] =
      ((((((-0.0001 *
                (((((((t461_tmp * t496 - t456_tmp * t500) + t204 * t500 * 2.0) -
                     t129 * t501) -
                    t72 * t496) +
                   t81 * t496) +
                  t148 * t501) +
                 t82 * t501) -
            t50 * t500) +
           t411_tmp_tmp * t496) +
          t114_tmp * t500) +
         t526 * t500 * 2.0) -
        t52 * t496) +
       t130 * t501) +
      t51 * t501;
  Jr[23] =
      ((((((0.0001 *
                (((((((-t38 * t203 * t454 + t204 * t454 * 2.0) - t129 * t455) +
                     t148 * t455) +
                    t44 * t46 * t48 * t58 * t447) +
                   t82 * t455) -
                  t16 * t44 * t46 * t49 * t58 * t447) +
                 t215 * t44 * t46 * t69 * t447) +
            t50 * t454) -
           t114_tmp * t454) -
          t526 * t454 * 2.0) -
         t130 * t455) -
        t150 * t455 * 2.0) -
       t410_tmp_tmp * t44 * t46 * t55 * t447) +
      t480_tmp * t44 * t46 * t49 * t58 * t447;
  t461_tmp = -t38 * (t11 - b_t152_tmp * t48 * t58);
  t456_tmp = q[7] * t38 * (t55 - 1.0);
  t204 = t11 * t39 * t76;
  t129 = t201 * t49 * t58;
  t72 = q[7] * t22 * t28 * t49 * t58;
  t215 = t201 * t11 * t39 * (t55 - 1.0);
  t201 = t201 * t28 * t38 * t55;
  t81 = q[8] * t6_tmp * t38 * t55;
  t82 = t6_tmp * t22 * t49 * t58;
  t410_tmp_tmp = t481_tmp * t49 * t58;
  Jr[24] =
      ((((((0.0001 * ((((((t461_tmp * t502 - t456_tmp * t503) + t204 * t502) +
                         t129 * t499) +
                        t72 * t503) +
                       t215 * t503) -
                      t201 * t499) +
            t50 * t503) +
           t81 * t499) -
          t82 * t503) -
         t115_tmp * t22 * t39 * (t55 - 1.0) * t503 * 2.0) -
        t410_tmp_tmp * t499) -
       t130 * t502) -
      t150 * t502 * 2.0;
  Jr[25] =
      ((((((-0.0001 * ((((((t461_tmp * t500 - t456_tmp * t501) + t204 * t500) -
                          t129 * t496) +
                         t72 * t501) +
                        t215 * t501) +
                       t201 * t496) -
            t50 * t501) +
           t81 * t496) +
          t82 * t501) -
         t410_tmp_tmp * t496) +
        t130 * t500) +
       t51 * t500) +
      t481_tmp * t11 * t39 * (t55 - 1.0) * t501;
  t461_tmp = q[8] * t41_tmp * t69;
  t456_tmp = t23 * t41_tmp * t55;
  t201 = t465_tmp * t14_tmp;
  t204 = q[8] * t40_tmp * t53;
  t115_tmp = t23 * t40_tmp * t53 * t55;
  t129 = b_t464_tmp * q[7] * q[8];
  t72 = t201 * t22;
  t215 = t465_tmp * t22;
  t81 = b_t160_tmp * t41_tmp * t42_tmp * t58;
  t82 = t457_tmp * t16;
  t50 = t457_tmp * t22;
  t410_tmp_tmp = t292 * t7;
  t411_tmp_tmp = t518 * q[8];
  t114_tmp = b_t160_tmp * t40_tmp * t42_tmp * t53 * t58;
  t526 = t464_tmp * q[7];
  t52 = t526 * q[2] * q[5] * q[8];
  t130 = t73 * q[2] * q[5] * q[8];
  t150 = b_t481_tmp * t22 * t42_tmp;
  t148 = b_t465_tmp * t22 * t40_tmp * t41_tmp * t53;
  t518 = t238_tmp * q[2] * q[5] * q[8] * t42_tmp;
  Jr[26] = t514_tmp * t39 * t44 *
           ((((((((((((((((((((((((((((t461_tmp * t100 + t461_tmp * t101) +
                                      t456_tmp * t100) +
                                     t456_tmp * t101) +
                                    t201 * t16 * t56) -
                                   t72 * t56) -
                                  t201 * t56 * t69) +
                                 t465_tmp * t16 * t56 * t71) -
                                t215 * t56 * t71) -
                               t465_tmp * t56 * t69 * t71) -
                              t204 * t68 * t69) -
                             t204 * t69 * t71) -
                            t115_tmp * t68) -
                           t115_tmp * t71) +
                          q[2] * t14_tmp * t22 * t42_tmp * t56 * t58) +
                         q[2] * t22 * t42_tmp * t56 * t58 * t71) -
                        t82 * t56) +
                       t50 * t56) -
                      t129 * t20_tmp * t56 * 2.0) +
                     t457_tmp * t56 * t69) -
                    t129 * t56 * t68 * 2.0) +
                   t72 * t55 * t56) +
                  t215 * t55 * t56 * t71) -
                 t81 * t100) -
                t81 * t101) +
               t130 * t8 * t56) +
              t82 * t54 * t56) +
             ((((((((((((((((((((-d * q[1] * q[4] * q[5] * t22 * t54 * t56 -
                                 t50 * t55 * t56) -
                                t457_tmp * t54 * t56 * t69) +
                               t410_tmp_tmp * t20_tmp * t55 * t56) +
                              t410_tmp_tmp * t55 * t56 * t68) -
                             t150 * t56 * t58) +
                            t411_tmp_tmp * t20_tmp * t42_tmp * t56 * t58) +
                           t411_tmp_tmp * t42_tmp * t56 * t58 * t68) +
                          b_t465_tmp * t16 * t40_tmp * t41_tmp * t53 * t57) -
                         t148 * t57) -
                        c_t465_tmp * t41_tmp * t53 * t57 * t69) +
                       t114_tmp * t68) +
                      t114_tmp * t71) -
                     t52 * t54 * t56 * 2.0) -
                    t52 * t55 * t56 * 2.0) +
                   t130 * t55 * t56 * t63) -
                  t518 * t56 * t58) +
                 t50 * t54 * t55 * t56) -
                t526 * q[8] * t40_tmp * t41_tmp * t53 * t57 * 2.0) +
               t150 * t54 * t56 * t58) +
              t148 * t55 * t57)) +
            (((q[5] * t22 * t40_tmp * t41_tmp * t42_tmp * t53 * t57 * t58 +
               t518 * t54 * t56 * t58) +
              t292 * t8 * t40_tmp * t41_tmp * t53 * t55 * t57) +
             t238_tmp * q[8] * t40_tmp * t41_tmp * t42_tmp * t53 * t57 * t58)) *
           ((L0 * d + d * q[9]) - 0.0001 * q[7]);
  t461_tmp = d * t48 * t58;
  t456_tmp = t73 * t38 * (t55 - 1.0);
  t457_tmp = b_t160_tmp * t38 * (t55 - 1.0);
  Jr[27] = (t461_tmp * t499 + t456_tmp * t502) + t457_tmp * t503;
  Jr[28] = (t461_tmp * t496 - t456_tmp * t500) - t457_tmp * t501;
  Jr[29] =
      (t456_tmp * t454 + t457_tmp * t455) - t171_tmp * t46 * t48 * t58 * t447;
  /*  t2 = cos(th); */
  /*  t3 = sin(th); */
  /*  t4 = L0+dL1; */
  /*  t5 = L0+dL2; */
  /*  t6 = L0+dL3; */
  /*  t7 = dx1.*2.0; */
  /*  t8 = dx2.*2.0; */
  /*  t9 = dy1.*2.0; */
  /*  t10 = dy2.*2.0; */
  /*  t11 = dx1.^2; */
  /*  t12 = dx1.^3; */
  /*  t13 = dx2.^2; */
  /*  t14 = dx2.^3; */
  /*  t15 = dx3.^2; */
  /*  t16 = dy1.^2; */
  /*  t17 = dy1.^3; */
  /*  t18 = dy2.^2; */
  /*  t19 = dy2.^3; */
  /*  t20 = dy3.^2; */
  /*  t25 = 1.0./d; */
  /*  t21 = dx1.*t2; */
  /*  t22 = dy1.*t2; */
  /*  t23 = dx1.*t3; */
  /*  t24 = dy1.*t3; */
  /*  t27 = t11+t16; */
  /*  t28 = t13+t18; */
  /*  t29 = t15+t20; */
  /*  t26 = -t24; */
  /*  t30 = t22+t23; */
  /*  t31 = 1.0./t27; */
  /*  t33 = 1.0./t28; */
  /*  t35 = 1.0./t29; */
  /*  t37 = sqrt(t27); */
  /*  t38 = sqrt(t28); */
  /*  t39 = sqrt(t29); */
  /*  t32 = t31.^2; */
  /*  t34 = t33.^2; */
  /*  t36 = t35.^2; */
  /*  t40 = t21+t26; */
  /*  t41 = 1.0./t37; */
  /*  t43 = 1.0./t38; */
  /*  t45 = 1.0./t39; */
  /*  t47 = t25.*t37; */
  /*  t48 = t25.*t38; */
  /*  t49 = t25.*t39; */
  /*  t42 = t41.^3; */
  /*  t44 = t43.^3; */
  /*  t46 = t45.^3; */
  /*  t50 = cos(t47); */
  /*  t51 = cos(t48); */
  /*  t52 = cos(t49); */
  /*  t53 = sin(t47); */
  /*  t54 = sin(t48); */
  /*  t55 = sin(t49); */
  /*  t56 = t50-1.0; */
  /*  t57 = t51-1.0; */
  /*  t58 = t52-1.0; */
  /*  t59 = t7.*t50; */
  /*  t60 = t8.*t51; */
  /*  t61 = t9.*t50; */
  /*  t62 = t10.*t51; */
  /*  t63 = t11.*t50; */
  /*  t64 = t13.*t51; */
  /*  t65 = t16.*t50; */
  /*  t66 = t18.*t51; */
  /*  t81 = t12.*t25.*t41.*t53; */
  /*  t82 = t14.*t25.*t43.*t54; */
  /*  t83 = t17.*t25.*t41.*t53; */
  /*  t84 = t19.*t25.*t43.*t54; */
  /*  t87 = dy1.*t4.*t21.*t42.*t53; */
  /*  t88 = dy1.*t4.*t23.*t42.*t53; */
  /*  t91 = dx1.*dx2.*t53.*t54; */
  /*  t92 = dy1.*dy2.*t53.*t54; */
  /*  t93 = dx1.*t16.*t25.*t41.*t53; */
  /*  t94 = dy1.*t11.*t25.*t41.*t53; */
  /*  t95 = dx2.*t18.*t25.*t43.*t54; */
  /*  t96 = dy2.*t13.*t25.*t43.*t54; */
  /*  t114 = t16.*t21.*t25.*t42.*t53; */
  /*  t115 = t11.*t22.*t25.*t42.*t53; */
  /*  t116 = t16.*t23.*t25.*t42.*t53; */
  /*  t117 = t11.*t24.*t25.*t42.*t53; */
  /*  t136 = t43.*t50.*t54; */
  /*  t139 = dx2.*dy2.*t44.*t50.*t54; */
  /*  t140 = t2.*t41.*t51.*t53; */
  /*  t141 = t3.*t41.*t51.*t53; */
  /*  t142 = dx2.*dy2.*t25.*t33.*t50.*t51; */
  /*  t144 = t30.*t41.*t51.*t53; */
  /*  t149 = t37.*t38.*t50.*t51; */
  /*  t150 = t40.*t41.*t51.*t53; */
  /*  t159 = dx2.*t2.*t41.*t43.*t53.*t54; */
  /*  t160 = dy2.*t2.*t41.*t43.*t53.*t54; */
  /*  t161 = dx2.*t3.*t41.*t43.*t53.*t54; */
  /*  t162 = dy2.*t3.*t41.*t43.*t53.*t54; */
  /*  t167 = d.*t3.*t5.*t41.*t43.*t53.*t54; */
  /*  t168 = d.*t2.*t5.*t41.*t43.*t53.*t54; */
  /*  t173 = t30.*t41.*t43.*t53.*t54; */
  /*  t176 = dx2.*dy2.*t30.*t41.*t44.*t53.*t54; */
  /*  t177 = t40.*t41.*t43.*t53.*t54; */
  /*  t182 = dx2.*dy2.*t40.*t41.*t44.*t53.*t54; */
  /*  t67 = t11+t65; */
  /*  t68 = t16+t63; */
  /*  t69 = t13+t66; */
  /*  t70 = t18+t64; */
  /*  t71 = t21.*t31.*t56; */
  /*  t72 = t22.*t31.*t56; */
  /*  t73 = t23.*t31.*t56; */
  /*  t74 = t24.*t31.*t56; */
  /*  t80 = t26.*t31.*t56; */
  /*  t85 = d.*t2.*t4.*t31.*t56; */
  /*  t86 = d.*t3.*t4.*t31.*t56; */
  /*  t101 = t2.*t7.*t16.*t32.*t56; */
  /*  t102 = dy1.*t7.*t21.*t32.*t56; */
  /*  t103 = t3.*t7.*t16.*t32.*t56; */
  /*  t104 = dy1.*t7.*t23.*t32.*t56; */
  /*  t105 = -t81; */
  /*  t106 = -t82; */
  /*  t107 = -t83; */
  /*  t108 = -t84; */
  /*  t118 = -t93; */
  /*  t119 = -t94; */
  /*  t120 = -t95; */
  /*  t121 = -t96; */
  /*  t122 = d.*t4.*t7.*t22.*t32.*t56; */
  /*  t127 = d.*t4.*t7.*t24.*t32.*t56; */
  /*  t137 = dx2.*t136; */
  /*  t138 = dy2.*t136; */
  /*  t143 = -t142; */
  /*  t153 = -t149; */
  /*  t158 = dx2.*dy2.*t33.*t41.*t53.*t57; */
  /*  t165 = dx1.*dx2.*dy1.*dy2.*t33.*t42.*t53.*t57; */
  /*  t169 = dx1.*dx2.*dy1.*dy2.*t25.*t31.*t33.*t50.*t57; */
  /*  t174 = dx2.*t173; */
  /*  t175 = dy2.*t173; */
  /*  t178 = dx2.*t177; */
  /*  t180 = dy2.*t177; */
  /*  t183 = -t176; */
  /*  t184 = dx2.*dy2.*t25.*t33.*t144; */
  /*  t191 = dx2.*dy2.*t25.*t33.*t150; */
  /*  t75 = dy1.*t71; */
  /*  t76 = dy1.*t73; */
  /*  t77 = -t71; */
  /*  t78 = -t72; */
  /*  t79 = -t73; */
  /*  t97 = t2.*t31.*t67; */
  /*  t98 = t2.*t31.*t68; */
  /*  t99 = t3.*t31.*t67; */
  /*  t100 = t3.*t31.*t68; */
  /*  t109 = -t85; */
  /*  t111 = t3.*t7.*t32.*t68; */
  /*  t113 = t3.*t9.*t32.*t68; */
  /*  t123 = t2.*t7.*t32.*t67; */
  /*  t125 = t2.*t9.*t32.*t67; */
  /*  t128 = t23.*t32.*t67.*-2.0; */
  /*  t129 = t24.*t32.*t67.*-2.0; */
  /*  t130 = t21.*t32.*t68.*-2.0; */
  /*  t131 = t22.*t32.*t68.*-2.0; */
  /*  t132 = t7+t118; */
  /*  t133 = t8+t120; */
  /*  t134 = t9+t119; */
  /*  t135 = t10+t121; */
  /*  t154 = t59+t105; */
  /*  t155 = t60+t106; */
  /*  t156 = t61+t107; */
  /*  t157 = t62+t108; */
  /*  t163 = dx1.*t158; */
  /*  t164 = dy1.*t158; */
  /*  t170 = dx1.*t33.*t41.*t53.*t70; */
  /*  t171 = dy1.*t33.*t41.*t53.*t69; */
  /*  t179 = -t174; */
  /*  t181 = -t175; */
  /*  t211 = t91+t92+t153; */
  /*  t145 = t2.*t31.*t132; */
  /*  t146 = t2.*t31.*t134; */
  /*  t147 = t3.*t31.*t132; */
  /*  t148 = t3.*t31.*t134; */
  /*  t185 = t2.*t31.*t154; */
  /*  t186 = t2.*t31.*t156; */
  /*  t187 = t3.*t31.*t154; */
  /*  t188 = t3.*t31.*t156; */
  /*  t189 = t76+t97; */
  /*  t190 = t75+t100; */
  /*  t200 = -dx2.*t43.*t54.*(t76-t98); */
  /*  t203 = -dx2.*dy2.*t33.*t57.*(t75-t99); */
  /*  t204 = dy2.*t43.*t54.*(t75-t99); */
  /*  t207 = dx2.*dy2.*t33.*t57.*(t76-t98); */
  /*  t208 = -t33.*t69.*(t75-t99); */
  /*  t210 = t33.*t70.*(t76-t98); */
  /*  t212 = t137+t164+t170; */
  /*  t213 = t138+t163+t171; */
  /*  t151 = -t145; */
  /*  t152 = -t148; */
  /*  t192 = -t186; */
  /*  t193 = -t187; */
  /*  t196 = dx2.*t43.*t54.*t190; */
  /*  t197 = dy2.*t43.*t54.*t189; */
  /*  t198 = dx2.*dy2.*t33.*t57.*t189; */
  /*  t199 = dx2.*dy2.*t33.*t57.*t190; */
  /*  t205 = t33.*t69.*t189; */
  /*  t206 = t33.*t70.*t190; */
  /*  t214 = t78+t102+t115+t128+t147; */
  /*  t215 = t79+t103+t116+t131+t146; */
  /*  t218 = t77+t101+t114+t129+t188; */
  /*  t219 = t80+t104+t117+t130+t185; */
  /*  t223 = t150+t200+t204; */
  /*  t226 = t178+t203+t210; */
  /*  t227 = t180+t207+t208; */
  /*  t216 = t77+t101+t113+t114+t152; */
  /*  t217 = t80+t104+t117+t123+t151; */
  /*  t220 = t78+t102+t111+t115+t193; */
  /*  t221 = t79+t103+t116+t125+t192; */
  /*  t222 = t144+t196+t197; */
  /*  t224 = t179+t198+t206; */
  /*  t225 = t181+t199+t205; */
  /*  et1 =
   * dx2.*t5.*t33.*t150-d.*t6.*t45.*t55.*(t25.*t178+t43.*t54.*(t76-t98)-t13.*t44.*t54.*(t76-t98)+t25.*t33.*t64.*(t76-t98)+dx2.*dy2.*t44.*t54.*(t75-t99)-dx2.*dy2.*t25.*t33.*t51.*(t75-t99))+d.*t5.*t33.*t57.*(t76-t98)-t5.*t13.*t44.*t54.*(t76-t98)-d.*dy3.*t6.*t35.*t58.*(t182-t191+t33.*t133.*(t75-t99)-dx2.*t34.*t69.*(t75-t99).*2.0-dy2.*t33.*t57.*(t76-t98)+dx2.*dy2.*t8.*t34.*t57.*(t76-t98)+dy2.*t13.*t25.*t44.*t54.*(t76-t98))+dx2.*dy2.*t5.*t44.*t54.*(t75-t99);
   */
  /*  et2 =
   * d.*dx3.*t6.*t35.*t58.*(t177+t33.*t155.*(t76-t98)-dx2.*t34.*t70.*(t76-t98).*2.0-dy2.*t33.*t57.*(t75-t99)-t13.*t40.*t41.*t44.*t53.*t54+t25.*t33.*t40.*t41.*t53.*t64+dx2.*dy2.*t8.*t34.*t57.*(t75-t99)+dy2.*t13.*t25.*t44.*t54.*(t75-t99))+d.*dx2.*dy2.*t5.*t34.*t57.*(t75-t99).*2.0-d.*dx2.*t5.*t8.*t34.*t57.*(t76-t98)-d.*dx2.*t5.*t40.*t41.*t44.*t53.*t54;
   */
  /*  et3 =
   * dy2.*t5.*t33.*t150-d.*t6.*t45.*t55.*(t25.*t180-t43.*t54.*(t75-t99)+t18.*t44.*t54.*(t75-t99)-t25.*t33.*t66.*(t75-t99)-dx2.*dy2.*t44.*t54.*(t76-t98)+dx2.*dy2.*t25.*t33.*t51.*(t76-t98))-d.*t5.*t33.*t57.*(t75-t99)+t5.*t18.*t44.*t54.*(t75-t99)+d.*dy3.*t6.*t35.*t58.*(t177-t33.*t157.*(t75-t99)+dx2.*t33.*t57.*(t76-t98)+dy2.*t34.*t69.*(t75-t99).*2.0-t8.*t18.*t34.*t57.*(t76-t98)-t18.*t40.*t41.*t44.*t53.*t54+t25.*t33.*t40.*t41.*t53.*t66-dx2.*t18.*t25.*t44.*t54.*(t76-t98))-dx2.*dy2.*t5.*t44.*t54.*(t76-t98);
   */
  /*  et4 =
   * d.*t5.*t18.*t34.*t57.*(t75-t99).*2.0+d.*dx3.*t6.*t35.*t58.*(-t182+t191+t33.*t135.*(t76-t98)-dx2.*t33.*t57.*(t75-t99)-dy2.*t34.*t70.*(t76-t98).*2.0+t8.*t18.*t34.*t57.*(t75-t99)+dx2.*t18.*t25.*t44.*t54.*(t75-t99))-d.*dy2.*t5.*t8.*t34.*t57.*(t76-t98)-d.*dy2.*t5.*t40.*t41.*t44.*t53.*t54;
   */
  /*  et5 =
   * dx1.*t4.*t31.*t50-d.*dx1.*t4.*t42.*t53+d.*dy3.*t6.*t35.*t58.*(t158-dx1.*dy1.*t33.*t42.*t53.*t69-dx2.*dy2.*t11.*t33.*t42.*t53.*t57+dx1.*dy1.*t25.*t31.*t33.*t50.*t69+dx2.*dy2.*t25.*t31.*t33.*t57.*t63-dx1.*dy2.*t25.*t41.*t43.*t53.*t54)+dx2.*t5.*t31.*t33.*t57.*t63-dx1.*t5.*t41.*t43.*t53.*t54-t6.*t31.*t43.*t45.*t55.*(dx2.*t54.*t63+dx1.*dy1.*dy2.*t50.*t54-d.*dx1.*t38.*t50.*t51+d.*dx2.*t37.*t53.*t54+dx1.*t37.*t38.*t51.*t53)-d.*dx3.*t6.*t35.*t58.*(t165-t169-t33.*t41.*t53.*t70+t25.*t41.*t43.*t91+t11.*t33.*t42.*t53.*t70-t25.*t31.*t33.*t63.*t70)+d.*dx2.*t5.*t33.*t41.*t53.*t57+dx1.*dy1.*dy2.*t5.*t31.*t33.*t50.*t57-d.*dx2.*t5.*t11.*t33.*t42.*t53.*t57+d.*dx1.*t6.*t42.*t43.*t45.*t55.*t211;
   */
  /*  et6 = -d.*dx1.*dy1.*dy2.*t5.*t33.*t42.*t53.*t57; */
  /*  et7 =
   * dy1.*t4.*t31.*t50-d.*dy1.*t4.*t42.*t53+d.*dx3.*t6.*t35.*t58.*(t158-dx1.*dy1.*t33.*t42.*t53.*t70-dx2.*dy2.*t16.*t33.*t42.*t53.*t57+dx1.*dy1.*t25.*t31.*t33.*t50.*t70+dx2.*dy2.*t25.*t31.*t33.*t57.*t65-dx2.*dy1.*t25.*t41.*t43.*t53.*t54)+dy2.*t5.*t31.*t33.*t57.*t65-dy1.*t5.*t41.*t43.*t53.*t54-t6.*t31.*t43.*t45.*t55.*(dy2.*t54.*t65+dx1.*dx2.*dy1.*t50.*t54-d.*dy1.*t38.*t50.*t51+d.*dy2.*t37.*t53.*t54+dy1.*t37.*t38.*t51.*t53)-d.*dy3.*t6.*t35.*t58.*(t165-t169-t33.*t41.*t53.*t69+t25.*t41.*t43.*t92+t16.*t33.*t42.*t53.*t69-t25.*t31.*t33.*t65.*t69)+d.*dy2.*t5.*t33.*t41.*t53.*t57+dx1.*dx2.*dy1.*t5.*t31.*t33.*t50.*t57-d.*dy2.*t5.*t16.*t33.*t42.*t53.*t57+d.*dy1.*t6.*t42.*t43.*t45.*t55.*t211;
   */
  /*  et8 = -d.*dx1.*dx2.*dy1.*t5.*t33.*t42.*t53.*t57; */
  /*  et9 =
   * dx2.*t5.*t33.*t50.*t51-dx2.*t5.*t41.*t44.*t92+d.*dx3.*t6.*t35.*t58.*(t136-t13.*t44.*t50.*t54+t25.*t33.*t50.*t64+dx1.*t33.*t41.*t53.*t155-t13.*t25.*t41.*t44.*t92-dx1.*dx2.*t34.*t41.*t53.*t70.*2.0+dy1.*dy2.*t33.*t41.*t53.*t57-dy1.*dy2.*t13.*t34.*t41.*t53.*t57.*2.0)-d.*dy3.*t6.*t35.*t58.*(t139+t143-dy1.*t33.*t41.*t53.*t133+dy1.*t8.*t34.*t41.*t53.*t69-dx1.*dy2.*t33.*t41.*t53.*t57+dy2.*t7.*t13.*t34.*t41.*t53.*t57+dx1.*dy2.*t13.*t25.*t41.*t44.*t53.*t54)-d.*dx2.*t5.*t44.*t50.*t54+d.*dx1.*t5.*t33.*t41.*t53.*t57-dx1.*t5.*t13.*t41.*t44.*t53.*t54-d.*t6.*t41.*t43.*t45.*t55.*(dx1.*t53.*t54+dx2.*t47.*t50.*t54-dx2.*t37.*t43.*t50.*t51+dx1.*t25.*t43.*t53.*t64+dx2.*dy1.*dy2.*t25.*t43.*t51.*t53);
   */
  /*  et10 =
   * d.*dx1.*t5.*t13.*t34.*t41.*t53.*t57.*-2.0+d.*dx2.*t6.*t41.*t44.*t45.*t55.*t211-d.*dx2.*dy1.*dy2.*t5.*t34.*t41.*t53.*t57.*2.0;
   */
  /*  et11 =
   * dy2.*t5.*t33.*t50.*t51-dy2.*t5.*t41.*t44.*t91+d.*dy3.*t6.*t35.*t58.*(t136-t18.*t44.*t50.*t54+t25.*t33.*t50.*t66+dy1.*t33.*t41.*t53.*t157-t18.*t25.*t41.*t44.*t91+dx1.*dx2.*t33.*t41.*t53.*t57-dy1.*dy2.*t34.*t41.*t53.*t69.*2.0-dx1.*dx2.*t18.*t34.*t41.*t53.*t57.*2.0)-d.*dx3.*t6.*t35.*t58.*(t139+t143-dx1.*t33.*t41.*t53.*t135+dy2.*t7.*t34.*t41.*t53.*t70-dx2.*dy1.*t33.*t41.*t53.*t57+dy1.*t8.*t18.*t34.*t41.*t53.*t57+dx2.*dy1.*t18.*t25.*t41.*t44.*t53.*t54)-d.*dy2.*t5.*t44.*t50.*t54+d.*dy1.*t5.*t33.*t41.*t53.*t57-dy1.*t5.*t18.*t41.*t44.*t53.*t54-d.*t6.*t41.*t43.*t45.*t55.*(dy1.*t53.*t54+dy2.*t47.*t50.*t54-dy2.*t37.*t43.*t50.*t51+dy1.*t25.*t43.*t53.*t66+dx1.*dx2.*dy2.*t25.*t43.*t51.*t53);
   */
  /*  et12 =
   * d.*dy1.*t5.*t18.*t34.*t41.*t53.*t57.*-2.0+d.*dy2.*t6.*t41.*t44.*t45.*t55.*t211-d.*dx1.*dx2.*dy2.*t5.*t34.*t41.*t53.*t57.*2.0;
   */
  /*  mt1 =
   * [d.*t4.*t72+d.*t4.*t73-d.*t5.*t173-d.*t6.*t45.*t55.*t222+d.*dx2.*t5.*t33.*t57.*t190+d.*dx3.*t6.*t35.*t58.*t224+d.*dy2.*t5.*t33.*t57.*t189+d.*dy3.*t6.*t35.*t58.*t225,d.*t4.*t74+d.*t4.*t77+d.*t5.*t177+d.*t6.*t45.*t55.*t223+d.*dx2.*t5.*t33.*t57.*(t76-t98)-d.*dy2.*t5.*t33.*t57.*(t75-t99)+d.*dx3.*t6.*t35.*t58.*t226+d.*dy3.*t6.*t35.*t58.*t227,0.0];
   */
  /*  mt2 =
   * [-t88+t109+t168+dx1.*t5.*t31.*t40.*t136+t2.*t4.*t11.*t42.*t53+d.*t6.*t45.*t55.*(t140+dx2.*t43.*t54.*t219-dy2.*t43.*t54.*t214-dx1.*t40.*t42.*t51.*t53+dx1.*t25.*t31.*t40.*t50.*t51)+d.*t4.*t7.*t21.*t32.*t56+d.*dx3.*t6.*t35.*t58.*(t159-t33.*t70.*t219-t40.*t42.*t43.*t91+dx2.*dy2.*t33.*t57.*t214+dx1.*t25.*t31.*t40.*t137)+d.*dy3.*t6.*t35.*t58.*(t160+t33.*t69.*t214-dx2.*dy2.*t33.*t57.*t219+dx1.*t25.*t31.*t40.*t138-dx1.*dy2.*t40.*t42.*t43.*t53.*t54)-d.*dx2.*t5.*t33.*t57.*t219-d.*dy1.*t4.*t23.*t32.*t56.*2.0+d.*dy2.*t5.*t33.*t57.*t214-d.*dx1.*t5.*t40.*t42.*t43.*t53.*t54];
   */
  /*  mt3 =
   * [-t86+t87+t122+t167-d.*t6.*t45.*t55.*(-t141+dx2.*t43.*t54.*t220+dy2.*t43.*t54.*t217+dx1.*t30.*t42.*t51.*t53-dx1.*t25.*t30.*t31.*t50.*t51)+dx1.*t5.*t30.*t31.*t136+t3.*t4.*t11.*t42.*t53+d.*t4.*t7.*t23.*t32.*t56+d.*dx3.*t6.*t35.*t58.*(t161+t33.*t70.*t220-t30.*t42.*t43.*t91+dx2.*dy2.*t33.*t57.*t217+dx1.*t25.*t30.*t31.*t137)+d.*dy3.*t6.*t35.*t58.*(t162+t33.*t69.*t217+dx2.*dy2.*t33.*t57.*t220+dx1.*t25.*t30.*t31.*t138-dx1.*dy2.*t30.*t42.*t43.*t53.*t54)+d.*dx2.*t5.*t33.*t57.*t220+d.*dy2.*t5.*t33.*t57.*t217-d.*dx1.*t5.*t30.*t42.*t43.*t53.*t54,et5+et6];
   */
  /*  mt4 =
   * [t86+t87+t122-t167+dy1.*t5.*t31.*t40.*t136-t3.*t4.*t16.*t42.*t53-d.*t6.*t45.*t55.*(t141-dx2.*t43.*t54.*t215+dy2.*t43.*t54.*t218+dy1.*t40.*t42.*t51.*t53-dy1.*t25.*t31.*t40.*t50.*t51)-d.*t3.*t4.*t16.*t32.*t56.*2.0-d.*dy3.*t6.*t35.*t58.*(t162-t33.*t69.*t218+t40.*t42.*t43.*t92+dx2.*dy2.*t33.*t57.*t215-dy1.*t25.*t31.*t40.*t138)-d.*dx3.*t6.*t35.*t58.*(t161+t33.*t70.*t215-dx2.*dy2.*t33.*t57.*t218-dy1.*t25.*t31.*t40.*t137+dx2.*dy1.*t40.*t42.*t43.*t53.*t54)-d.*dx2.*t5.*t33.*t57.*t215+d.*dy2.*t5.*t33.*t57.*t218-d.*dy1.*t5.*t40.*t42.*t43.*t53.*t54];
   */
  /*  mt5 =
   * [t88+t109+t127+t168-d.*t6.*t45.*t55.*(-t140+dx2.*t43.*t54.*t216+dy2.*t43.*t54.*t221+dy1.*t30.*t42.*t51.*t53-dy1.*t25.*t30.*t31.*t50.*t51)+dy1.*t5.*t30.*t31.*t136+t2.*t4.*t16.*t42.*t53+d.*t4.*t9.*t22.*t32.*t56+d.*dy3.*t6.*t35.*t58.*(t160+t33.*t69.*t221-t30.*t42.*t43.*t92+dx2.*dy2.*t33.*t57.*t216+dy1.*t25.*t30.*t31.*t138)+d.*dx3.*t6.*t35.*t58.*(t159+t33.*t70.*t216+dx2.*dy2.*t33.*t57.*t221+dy1.*t25.*t30.*t31.*t137-dx2.*dy1.*t30.*t42.*t43.*t53.*t54)+d.*dx2.*t5.*t33.*t57.*t216+d.*dy2.*t5.*t33.*t57.*t221-d.*dy1.*t5.*t30.*t42.*t43.*t53.*t54,et7+et8,-d.*t31.*t40.*t56,-d.*t30.*t31.*t56,d.*t41.*t53,et1+et2];
   */
  /*  mt6 =
   * [dx2.*t5.*t33.*t144-d.*t6.*t45.*t55.*(t25.*t174-t43.*t54.*t190+t13.*t44.*t54.*t190-t25.*t33.*t64.*t190+dx2.*dy2.*t44.*t54.*t189-dx2.*dy2.*t25.*t33.*t51.*t189)-d.*t5.*t33.*t57.*t190+t5.*t13.*t44.*t54.*t190+d.*dx3.*t6.*t35.*t58.*(t173-t33.*t155.*t190-dy2.*t33.*t57.*t189+t8.*t34.*t70.*t190+dy2.*t13.*t25.*t44.*t54.*t189-t13.*t30.*t41.*t44.*t53.*t54+t25.*t30.*t33.*t41.*t53.*t64+dx2.*dy2.*t8.*t34.*t57.*t189)+d.*dy3.*t6.*t35.*t58.*(t183+t184-t33.*t133.*t189-dy2.*t33.*t57.*t190+t8.*t34.*t69.*t189+dy2.*t13.*t25.*t44.*t54.*t190+dx2.*dy2.*t8.*t34.*t57.*t190)+dx2.*dy2.*t5.*t44.*t54.*t189+d.*dx2.*t5.*t8.*t34.*t57.*t190+d.*dy2.*t5.*t8.*t34.*t57.*t189-d.*dx2.*t5.*t30.*t41.*t44.*t53.*t54,et9+et10];
   */
  /*  mt7 =
   * [et3+et4,dy2.*t5.*t33.*t144-d.*t6.*t45.*t55.*(t25.*t175-t43.*t54.*t189+t18.*t44.*t54.*t189-t25.*t33.*t66.*t189+dx2.*dy2.*t44.*t54.*t190-dx2.*dy2.*t25.*t33.*t51.*t190)-d.*t5.*t33.*t57.*t189+t5.*t18.*t44.*t54.*t189+d.*dy3.*t6.*t35.*t58.*(t173-t33.*t157.*t189-dx2.*t33.*t57.*t190+t10.*t34.*t69.*t189+t8.*t18.*t34.*t57.*t190+dx2.*t18.*t25.*t44.*t54.*t190-t18.*t30.*t41.*t44.*t53.*t54+t25.*t30.*t33.*t41.*t53.*t66)+d.*dx3.*t6.*t35.*t58.*(t183+t184-t33.*t135.*t190-dx2.*t33.*t57.*t189+t10.*t34.*t70.*t190+t8.*t18.*t34.*t57.*t189+dx2.*t18.*t25.*t44.*t54.*t189)+dx2.*dy2.*t5.*t44.*t54.*t190+d.*dy2.*t5.*t8.*t34.*t57.*t190+d.*dy2.*t5.*t10.*t34.*t57.*t189-d.*dy2.*t5.*t30.*t41.*t44.*t53.*t54,et11+et12];
   */
  /*  mt8 =
   * [d.*t177+d.*dx2.*t33.*t57.*(t76-t98)-d.*dy2.*t33.*t57.*(t75-t99),d.*t173-d.*dx2.*t33.*t57.*t190-d.*dy2.*t33.*t57.*t189,d.*t136+d.*dx1.*dx2.*t33.*t41.*t53.*t57+d.*dy1.*dy2.*t33.*t41.*t53.*t57,d.*t6.*t35.*t58.*t226+dx3.*t6.*t35.*t52.*t223-t6.*t15.*t46.*t55.*t226-d.*t6.*t15.*t36.*t58.*t226.*2.0-d.*dx3.*t6.*t46.*t55.*t223-dx3.*dy3.*t6.*t46.*t55.*t227-d.*dx3.*dy3.*t6.*t36.*t58.*t227.*2.0,-d.*t6.*t35.*t58.*t224+dx3.*t6.*t35.*t52.*t222+t6.*t15.*t46.*t55.*t224+d.*t6.*t15.*t36.*t58.*t224.*2.0-d.*dx3.*t6.*t46.*t55.*t222+dx3.*dy3.*t6.*t46.*t55.*t225+d.*dx3.*dy3.*t6.*t36.*t58.*t225.*2.0];
   */
  /*  mt9 =
   * [d.*t6.*t35.*t58.*t212-t6.*t15.*t46.*t55.*t212-d.*t6.*t15.*t36.*t58.*t212.*2.0-dx3.*dy3.*t6.*t46.*t55.*t213-d.*dx3.*dy3.*t6.*t36.*t58.*t213.*2.0-dx3.*t6.*t35.*t41.*t43.*t52.*t211+d.*dx3.*t6.*t41.*t43.*t46.*t55.*t211,d.*t6.*t35.*t58.*t227+dy3.*t6.*t35.*t52.*t223-t6.*t20.*t46.*t55.*t227-d.*t6.*t20.*t36.*t58.*t227.*2.0-d.*dy3.*t6.*t46.*t55.*t223-dx3.*dy3.*t6.*t46.*t55.*t226-d.*dx3.*dy3.*t6.*t36.*t58.*t226.*2.0,-d.*t6.*t35.*t58.*t225+dy3.*t6.*t35.*t52.*t222+t6.*t20.*t46.*t55.*t225+d.*t6.*t20.*t36.*t58.*t225.*2.0-d.*dy3.*t6.*t46.*t55.*t222+dx3.*dy3.*t6.*t46.*t55.*t224+d.*dx3.*dy3.*t6.*t36.*t58.*t224.*2.0];
   */
  /*  mt10 =
   * [d.*t6.*t35.*t58.*t213-t6.*t20.*t46.*t55.*t213-d.*t6.*t20.*t36.*t58.*t213.*2.0-dx3.*dy3.*t6.*t46.*t55.*t212-d.*dx3.*dy3.*t6.*t36.*t58.*t212.*2.0-dy3.*t6.*t35.*t41.*t43.*t52.*t211+d.*dy3.*t6.*t41.*t43.*t46.*t55.*t211,d.*t45.*t55.*t223+d.*dx3.*t35.*t58.*t226+d.*dy3.*t35.*t58.*t227,d.*t45.*t55.*t222-d.*dx3.*t35.*t58.*t224-d.*dy3.*t35.*t58.*t225,d.*dx3.*t35.*t58.*t212+d.*dy3.*t35.*t58.*t213-d.*t41.*t43.*t45.*t55.*t211];
   */
  /*  Jr = reshape([mt1,mt2,mt3,mt4,mt5,mt6,mt7,mt8,mt9,mt10],3,10); */
  t457_tmp = t40_tmp / d;
  t72 = cos(t457_tmp);
  t130 = t41_tmp / d;
  t292 = sin(t130);
  t150 = cos(t130);
  t130 = t18_tmp + t12_tmp * t72;
  t148 = t253_tmp_tmp * t3_tmp * (t72 - 1.0) / t30_tmp;
  t518 = t2_tmp * t130 / t30_tmp - t148;
  t73 = t253_tmp_tmp * t2_tmp * (t72 - 1.0) / t30_tmp;
  t411_tmp_tmp = t12_tmp + t18_tmp * t72;
  t114_tmp = t3_tmp * t411_tmp_tmp / t30_tmp - t73;
  t461_tmp = t42_tmp / d;
  t129 = sin(t457_tmp);
  t456_tmp = cos(t461_tmp) - 1.0;
  t410_tmp_tmp = t160_tmp * (t150 - 1.0);
  t461_tmp = d * sin(t461_tmp) * t6_tmp;
  t82 = q[4] * t292;
  t50 = q[5] * t292;
  t115_tmp = t150 * t129;
  t81 = t202 * (t150 - 1.0);
  t171_tmp = t205 * (t150 - 1.0);
  t526 = t480_tmp * t456_tmp;
  t238_tmp = t20_tmp + t14_tmp * t150;
  t204 = q[4] * t129 * t292;
  t456_tmp *= t481_tmp;
  t51 = t14_tmp + t20_tmp * t150;
  t52 = q[5] * t129 * t292;
  t457_tmp = d * t129;
  t201 = t457_tmp * t292 * t5_tmp;
  x_r[0] =
      ((((((t461_tmp *
                ((t82 * t518 / t41_tmp - t50 * t114_tmp / t41_tmp) +
                 t115_tmp * t43_tmp / t40_tmp) /
                t42_tmp -
            t81 * t518 / t31_tmp) +
           t171_tmp * t114_tmp / t31_tmp) -
          b_t464_tmp * t2_tmp * t4_tmp * (t72 - 1.0) / t30_tmp) +
         t465_tmp * t3_tmp * t4_tmp * (t72 - 1.0) / t30_tmp) +
        t526 *
            ((t410_tmp_tmp * t114_tmp / t31_tmp - t238_tmp * t518 / t31_tmp) +
             t204 * t43_tmp / t447_tmp) /
            t32_tmp) +
       t456_tmp *
           ((t51 * t114_tmp / t31_tmp - t410_tmp_tmp * t518 / t31_tmp) +
            t52 * t43_tmp / t447_tmp) /
           t32_tmp) +
      t201 * t43_tmp / t447_tmp;
  t518 = t3_tmp * t130 / t30_tmp + t73;
  t114_tmp = t2_tmp * t411_tmp_tmp / t30_tmp + t148;
  x_r[1] =
      ((((((t461_tmp *
                ((t82 * t518 / t41_tmp + t50 * t114_tmp / t41_tmp) +
                 t115_tmp * t33_tmp / t40_tmp) /
                t42_tmp -
            t81 * t518 / t31_tmp) -
           t171_tmp * t114_tmp / t31_tmp) -
          t465_tmp * t2_tmp * t4_tmp * (t72 - 1.0) / t30_tmp) -
         b_t464_tmp * t3_tmp * t4_tmp * (t72 - 1.0) / t30_tmp) -
        t526 *
            ((t238_tmp * t518 / t31_tmp + t410_tmp_tmp * t114_tmp / t31_tmp) -
             t204 * t33_tmp / t447_tmp) /
            t32_tmp) -
       t456_tmp *
           ((t51 * t114_tmp / t31_tmp + t410_tmp_tmp * t518 / t31_tmp) -
            t52 * t33_tmp / t447_tmp) /
           t32_tmp) +
      t201 * t33_tmp / t447_tmp;
  t518 = t40_tmp * t31_tmp;
  x_r[2] =
      (((((t457_tmp * t4_tmp / t40_tmp + d * t72 * t292 * t5_tmp / t41_tmp) +
          t526 *
              ((q[4] * t72 * t292 / t41_tmp + q[1] * t129 * t238_tmp / t518) +
               b_t480_tmp * t129 * (t150 - 1.0) / t518) /
              t32_tmp) +
         t456_tmp *
             ((q[5] * t72 * t292 / t41_tmp + q[2] * t129 * t51 / t518) +
              b_t481_tmp * t129 * (t150 - 1.0) / t518) /
             t32_tmp) -
        t461_tmp *
            ((t213_tmp * t129 * t292 - t72 * t150 * t40_tmp * t41_tmp) +
             t217_tmp * t129 * t292) /
            (t447_tmp * t42_tmp)) +
       t216_tmp * t129 * t5_tmp * (t150 - 1.0) / t518) +
      t465_tmp * q[5] * t129 * t5_tmp * (t150 - 1.0) / t518;
}

/*
 * File trailer for J_r.c
 *
 * [EOF]
 */
